# Generated by Django 4.1.1 on 2023-03-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_contactus_alter_post_content"),
    ]

    operations = [
        migrations.DeleteModel(name="contactUs",),
    ]
